import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
          <header className="bg-blue-500 p-4">
            <h1 className="text-white text-2xl font-bold">My App</h1>
          </header>
          <main className="flex-grow p-4">{children}</main>
          <footer className="bg-blue-500 p-4">
            <p className="text-white">Footer content here</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
